# Importing files

The output format in this machine is different from what PlateMate originally was able to read. Thus, we will extend its reading module. To achieve this, we explore below openpyxl as an option to read directly from the xlsx files provided by the plate reader.

In [3]:
import numpy as np
import pylab as pl
import openpyxl as xl
import string
%matplotlib inline

In [4]:
dataset_folder = "../datasets/"

read = xl.load_workbook(dataset_folder + "20161003 pJP22mcherry 01.xlsx")['Sheet2']

In [5]:
print read['B74'].value

25386


All plate readings start in cells B36, B74, B106 and B144. It would be interesting to have a better documentation of what is the difference among each of these readings -- of course, it's got to be something related to the wavelengths used in the excitation and emission.

Let's write a function that reads a plate given its starting point and the number of columns to be considered.

In [6]:
def readPlate( spsheet, InitialRow, ncols = 12, nrows = 8 ):
    
    read = np.zeros( (nrows, ncols) )
    
    LTS = list(string.ascii_uppercase)[1:20]
    for row in range(nrows):
        line = row + InitialRow
        for col in range(ncols):
            read[row,col] = float( spsheet[LTS[col]+str(line)].value )
    
    return read

Let's check the first two:

In [7]:
readPlate(read, 36)

array([[  5906.,   4512.,   4368.,   5048.,   4359.,   4401.,   4593.,
          5385.,  21265.,   4597.,   4691.,   4055.],
       [  5173.,   5054.,   4633.,   4652.,   4059.,   4925.,   4277.,
          4698.,   3432.,   4438.,   4934.,   3196.],
       [  3747.,   4047.,   4370.,   4511.,   3921.,   3949.,   3538.,
          5852.,   4047.,   3053.,   3571.,   5200.],
       [  4883.,   6831.,   5012.,   4473.,   4293.,   4544.,   3984.,
          5956.,   5035.,   3884.,   3481.,   4102.],
       [  4961.,   3784.,   3967.,   4668.,   4705.,   4989.,   4605.,
          5016.,   4607.,   4671.,   5061.,   5908.],
       [  7107.,   4283.,   3522.,   4044.,   5243.,   7759.,   5748.,
          4054.,   4662.,   4662.,   4426.,   4633.],
       [  4462.,   3906.,   5069.,   4531.,   4582.,   4111.,   4165.,
          3917.,   4880.,   4346.,   4041.,   3217.],
       [  5464.,   5627.,   4384.,   4112.,   3809.,   4688.,   4655.,
          3650.,   3925.,  28013.,  29253.,  29582.]])

In [8]:
readPlate(read, 74)

array([[ 25386.,  20823.,  21310.,  23226.,  21077.,  23416.,  21139.,
         22382.,  29034.,  22155.,  23189.,  20868.],
       [ 21956.,  23143.,  21927.,  20774.,  20379.,  22115.,  21913.,
         21479.,  20712.,  21162.,  24108.,  19548.],
       [ 33122.,  20318.,  22968.,  20900.,  20130.,  21736.,  20205.,
         27239.,  21484.,  20628.,  23277.,  23634.],
       [ 21493.,  25746.,  24405.,  22876.,  27636.,  21945.,  24254.,
         25211.,  24127.,  20495.,  20743.,  20793.],
       [ 22136.,  19682.,  19713.,  19901.,  23398.,  21508.,  20978.,
         21934.,  20435.,  22058.,  21023.,  28136.],
       [ 20542.,  21462.,  19706.,  20584.,  24527.,  27999.,  23953.,
         22196.,  23252.,  23433.,  24606.,  22406.],
       [ 20419.,  20087.,  22247.,  20670.,  20018.,  21292.,  20081.,
         20428.,  22260.,  20785.,  21575.,  21532.],
       [ 21374.,  24934.,  19825.,  19963.,  19279.,  19034.,  19933.,
         20249.,  21203.,  31340.,  28922.,  29218.]])

All we need to do now is to parse it into a pandas dataframe. To do that, it is helpful to reshape this numpy array into a single line.

In [10]:
? np.reshape

In [11]:
X = readPlate(read, 74)
print X.shape

np.reshape(X, (X.shape[0]*X.shape[1]) )

(8, 12)


array([ 25386.,  20823.,  21310.,  23226.,  21077.,  23416.,  21139.,
        22382.,  29034.,  22155.,  23189.,  20868.,  21956.,  23143.,
        21927.,  20774.,  20379.,  22115.,  21913.,  21479.,  20712.,
        21162.,  24108.,  19548.,  33122.,  20318.,  22968.,  20900.,
        20130.,  21736.,  20205.,  27239.,  21484.,  20628.,  23277.,
        23634.,  21493.,  25746.,  24405.,  22876.,  27636.,  21945.,
        24254.,  25211.,  24127.,  20495.,  20743.,  20793.,  22136.,
        19682.,  19713.,  19901.,  23398.,  21508.,  20978.,  21934.,
        20435.,  22058.,  21023.,  28136.,  20542.,  21462.,  19706.,
        20584.,  24527.,  27999.,  23953.,  22196.,  23252.,  23433.,
        24606.,  22406.,  20419.,  20087.,  22247.,  20670.,  20018.,
        21292.,  20081.,  20428.,  22260.,  20785.,  21575.,  21532.,
        21374.,  24934.,  19825.,  19963.,  19279.,  19034.,  19933.,
        20249.,  21203.,  31340.,  28922.,  29218.])